#include<WiFi.h>//libraryforwifi
#include<PubSubClient.h>//libraryforMQTT
#include<LiquidCrystal_I2C.h>
LiquidCrystal_I2Clcd(0x27,20,4);
//-----------------------credentialsofIBMAccounts-----------------------------
//IBMorganisationid
#defineDEVICE_TYPE"abcd"//Devicetypementionedinibmwatsoniotplatform
#defineDEVICE_ID"1234"//DeviceIDmentionedinibmwatsoniotplatform
#defineTOKEN"12345678"//Token
//-----------------------customiseabovevalues----------------------------------------------------
charserver[]=ORG".messaging.internetofthings.ibmcloud.com";//servername
charpublishTopic[]="iot-2/evt/data/fmt/json";//topicnameandtypeofevent performandformatin
whichdatatobesend
chartopic[]="iot-2/cmd/led/fmt/String";//cmdRepresenttypeandcommandistest formatof
strings
charauthMethod[]="use-token-auth";//authenticationmethod
chartoken[]=TOKEN;
charclientId[]="d:"ORG":"DEVICE_TYPE":"DEVICE_ID;//Clientid
//--------------------------------------------------------------------------------------------------------------------
WiFiClientwifiClient;//creatinginstanceforwificlient
PubSubClientclient(server,1883,wifiClient);
#defineECHO_PIN12
#defineTRIG_PIN13
floatdist;
voidsetup()
{
Serial.begin(115200);
pinMode(LED_BUILTIN,OUTPUT);
pinMode(TRIG_PIN,OUTPUT);
pinMode(ECHO_PIN,INPUT);
//pirpin
#defineORG"wjmfdn"
pinMode(34,INPUT);
//ledpins
pinMode(23,OUTPUT);
pinMode(2,OUTPUT);
pinMode(4,OUTPUT);
pinMode(15,OUTPUT);
lcd.init();
lcd.backlight();
lcd.setCursor(1,0);
lcd.print("");
wifiConnect();
mqttConnect();
}
floatreadcmCM()
{
digitalWrite(TRIG_PIN,LOW);
delayMicroseconds(2);
digitalWrite(TRIG_PIN,HIGH);
delayMicroseconds(10);
digitalWrite(TRIG_PIN,LOW);
intduration=pulseIn(ECHO_PIN,HIGH);
returnduration*0.034/2;
}
voidloop()
{
lcd.clear();
publishData();
delay(500);
if(!client.loop())
{
mqttConnect();//functioncalltoconnecttoIBM
}
}
/*--------------------------------retrievingtocloud-----------------------------------------------------*/
voidwifiConnect()
{
Serial.print("Connectingto");
Serial.print("Wifi");
WiFi.begin("Wokwi-GUEST","",6);
while(WiFi.status()!=WL_CONNECTED)
{
delay(500);
Serial.print(".");
}
Serial.print("WiFiconnected,IPaddress:");
Serial.println(WiFi.localIP());
}
voidmqttConnect()
{
if(!client.connected())
{
Serial.print("ReconnectingMQTTclientto");
Serial.println(server);
while(!client.connect(clientId,authMethod,token))
{
Serial.print(".");
delay(500);
}
initManagedDevice();
Serial.println();
}
}
voidinitManagedDevice()
{
if(client.subscribe(topic))
{
Serial.println("IBMsubscribetocmdOK");
}
else
{
Serial.println("subscribetocmdFAILED");
}
}
voidpublishData()
{
floatcm=readcmCM();
if(digitalRead(34))//pirmotiondetection
{
Serial.println("MotionDetected");
Serial.println("LidOpened");
digitalWrite(15,HIGH);
if(digitalRead(34)==true)
{
if(cm<=60)//Binleveldetection
{
digitalWrite(2,HIGH);
Serial.println("HighAlert!!!,Trashbinisabouttobefull");
Serial.println("LidClosed");
lcd.print("Full!Don'tuse");
delay(2000);
lcd.clear();
digitalWrite(4,LOW);
digitalWrite(23,LOW);
}
elseif(cm>60&&cm<120)
{
digitalWrite(4,HIGH);
Serial.println("Warning!!,Trashisabouttocross50%ofbinlevel");
digitalWrite(2,LOW);
digitalWrite(23,LOW);
}
elseif(cm>120)
{
digitalWrite(23,HIGH);
Serial.println("Binisavailable");
digitalWrite(2,LOW);
digitalWrite(4,LOW);
}
delay(10000);
Serial.println("LidClosed");
}
else
{
Serial.println("Nomotiondetected");
digitalWrite(2,LOW);
digitalWrite(15,LOW);
digitalWrite(4,LOW);
digitalWrite(23,LOW);
}
}
else
{
digitalWrite(15,LOW);
}
if(cm<=60)
{
digitalWrite(21,HIGH);
Stringpayload="{\"High_Alert\":";
payload+=cm;
payload+="}";
Serial.print("\n");
Serial.print("Sendingpayload:");
Serial.println(payload);
if(client.publish(publishTopic,(char*)payload.c_str()))//ifdataisuploadedtocloud successfully,printspublishok
elseprintspublishfailed
{
Serial.println("PublishOK");
}
}
elseif(cm<=120)
{
digitalWrite(22,HIGH);
Stringpayload="{\"Warning\":";
payload+=cm;
payload+="}";
Serial.print("\n");
Serial.print("Sendingpayload:");
Serial.println(payload);
if(client.publish(publishTopic,(char*)payload.c_str()))
{
Serial.println("PublishOK");
}
else
{
Serial.println("PublishFAILED");
}
}
else
{
Serial.println();
}
floatinches=(cm/2.54);//printonlcd
lcd.setCursor(0,0);
lcd.print("Inches");
lcd.setCursor(4,0);
lcd.setCursor(12,0);
lcd.print("cm");
lcd.setCursor(1,1);
lcd.print(inches,1);
lcd.setCursor(11,1);
lcd.print(cm,1);
lcd.setCursor(14,1);
delay(1000);
lcd.clear();
}
